source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'hedvig' do
  pod 'React',
    :path => "../node_modules/@hedviginsurance/react-native",
    :inhibit_warnings => true,
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge",
      "RCTLinkingIOS"
    ]
  pod 'yoga',
    :path => "../node_modules/@hedviginsurance/react-native/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "../node_modules/@hedviginsurance/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/@hedviginsurance/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "../node_modules/@hedviginsurance/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true

  pod 'react-native-branch', :path => '../node_modules/react-native-branch'
  pod 'Branch-SDK', :path => '../node_modules/react-native-branch/ios'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNAudio', :path => '../node_modules/react-native-audio'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Firestore'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Performance'
  pod 'Fabric', '~> 1.7.11'
  pod 'Crashlytics', '~> 3.10.7'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-config', :path => '../node_modules/@hedviginsurance/react-native-config'
  pod 'ReactNativeNavigation', :path => '../node_modules/@hedviginsurance/react-native-navigation'
  pod 'ReactNativeAnalyticsSegmentIo', :path => '../node_modules/react-native-analytics-segment-io'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/ios'
  pod 'ReactNativeHeicConverter', :path => '../node_modules/react-native-heic-converter'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNFS', :path => '../node_modules/@hedviginsurance/react-native-fs'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'react-native-document-picker', :path => '../node_modules/@hedviginsurance/react-native-document-picker'

  ## Pods from ugglan
  pod 'DeviceKit', '~> 2.0'
  pod 'lottie-ios', '~> 2.5.3'
  pod 'SwiftLint'
  pod 'DynamicColor', '~> 4.0.2'
  pod 'SwiftFormat/CLI'
  pod 'Apollo'
  pod 'Apollo/WebSocket'
  pod 'Disk', '~> 0.6.3'
  pod 'FlowFramework', git: 'https://github.com/hedviginsurance/flow.git'
  pod 'PresentationFramework', git: 'https://github.com/hedviginsurance/presentation.git'
  pod 'FormFramework/Presentation', git: 'https://github.com/hedviginsurance/form.git'
  pod 'FormFramework', git: 'https://github.com/hedviginsurance/form.git'
  pod 'SnapKit', '~> 5.0.0'
  pod 'UICollectionView+AnimatedScroll', git: 'https://github.com/HedvigInsurance/UICollectionView-AnimatedScroll.git'
  pod 'FlowFeedback', git: 'https://github.com/HedvigInsurance/FlowFeedback.git'
  pod 'SwiftGen'
  pod 'Firebase/Core'
  pod 'AcknowList'
  pod 'MarkdownKit'
  pod 'Ease', git: 'https://github.com/hedviginsurance/ease.git'

  post_install do |installer|
    system("cd hedvig/ugglan; ../../Pods/SwiftGen/bin/swiftgen")
    system("cd hedvig/ugglan; /usr/local/bin/swiftTranslationsCodegen --projects '[App, IOS]' --destination 'Src/Assets/Localization/Localization.swift'")
    system("cd hedvig/ugglan; sh scripts/update-graphql-schema.sh")
    system("CONFIGURATION=\"DEBUG\" sh Pods/Apollo/scripts/check-and-run-apollo-cli.sh codegen:generate --queries=\"$(find . -name '*.graphql')\"  --schema=hedvig/ugglan/Src/Data/schema.json hedvig/ugglan/Src/Data/API.swift")

    installer.pods_project.build_configurations.each do |config|
      if config.name.start_with?("Debug")
        config.build_settings["GCC_PREPROCESSOR_DEFINITIONS"].push("DEBUG=1")
        config.build_settings["GCC_OPTIMIZATION_LEVEL"] = 0
        config.build_settings["DEBUG_INFORMATION_FORMAT"] = "dwarf"
        config.build_settings["SWIFT_ACTIVE_COMPILATION_CONDITIONS"] = "DEBUG"
        config.build_settings["MTL_ENABLE_DEBUG_INFO"] = "YES"
      end
    end
  end
end
